service: lambda-env

package:
  artifact: s3://amytest123/

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-1

functions:
  hello:
    handler: src/handler.generateRandomNumber
    timeout: 60 # seconds
    memorySize: 128 # mb
  hi:
    handler: src/handler.generateRandomNumber
    timeout: 60 # seconds
    memorySize: 128 # mb    
